# Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---
# Dev Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---